### ISSUE TITLE
Automatically detect and report sample levels

### ISSUE THREAD

**Issue by happycube** [simoninns/DomesdayDuplicator#101] opened 2019-12-31 06:36 UTC
Gamnn had an issue where ld-decode DoD was being triggered by very high sample levels (I backed that out tonight), which made me think it'd be nice to report that the incoming signal levels are too high.

Also, it would be good to confirm that *something* is being captured.

**Comment by lizardgai4** [comment] 2022-08-11 06:20
Is this a duplicate of https://github.com/simoninns/DomesdayDuplicator/issues/25 ?

**Comment by simoninns** [comment] 2022-08-29 06:41
Duplicate of issue #25

**Closed by simoninns** 2022-08-29 06:41 UTC
