### ISSUE TITLE
Block headers / checksums in data

### ISSUE THREAD

**Issue by wondras** [simoninns/DomesdayDuplicator#39] opened 2018-09-11 22:59 UTC
Currently there is no way to verify that no data was lost or corrupted during capture. This could be addressed by having the FPGA add some form of block headers containing index numbers, along with a checksum at the end of the block. 

If the blocks are not synchronized so they appear at specific positions in the data, a 'magic number' could precede the block header, so it can be found regardless of position.

**Comment by simoninns** [comment] 2018-09-24 18:47
It is possible to implement this; but it requires some fairly complex modifications to the FPGA code.  The reason why there is currently no checking is because it's not really required.  The FPGA<->FX3 is a synchronous databus and any failure to communicate would bring the whole capture process to a halt (and could only really be caused by a fault in the electronics/connections and is therefore unlikely).  The FX3 to USB3 host communication is guaranteed by the transport of the USB3 protocols.

If (now far more boards are in use) there is any evidence of communication failure, I'll revisit this - but for the time being it's a close-won't fix.

**Closed by simoninns** 2018-09-24 18:47 UTC
Labels: enhancement, wontfix
